-- 코드를 입력하세요
SELECT a2.ANIMAL_ID, a2.ANIMAL_TYPE, a2.NAME
FROM ANIMAL_INS a1 INNER JOIN ANIMAL_OUTS a2
ON a1.ANIMAL_ID = a2.ANIMAL_ID
WHERE a1.SEX_UPON_INTAKE LIKE '%Intact%' AND (a2.SEX_UPON_OUTCOME LIKE '%Neutered%' OR a2.SEX_UPON_OUTCOME LIKE '%Spayed%')
ORDER BY a2.ANIMAL_ID;