-- 코드를 입력하세요
SELECT f1.PRODUCT_ID, f1.PRODUCT_NAME, SUM(f2.AMOUNT * f1.PRICE) as TOTAL_SALES
FROM FOOD_PRODUCT f1 LEFT JOIN FOOD_ORDER f2
ON f1.PRODUCT_ID = f2.PRODUCT_ID
WHERE f2.PRODUCE_DATE LIKE '2022-05%'
GROUP BY f1.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, f1.PRODUCT_ID;