-- 코드를 입력하세요
SELECT u1.TITLE, u1.BOARD_ID, u2.REPLY_ID, u2.WRITER_ID, u2.CONTENTS, DATE_FORMAT(u2.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as u1 
INNER JOIN USED_GOODS_REPLY as u2
ON u1.BOARD_ID = u2.BOARD_ID
WHERE u1.CREATED_DATE LIKE '2022-10%'
ORDER BY u2.CREATED_DATE, u1.TITLE;
