-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD u1 RIGHT JOIN USED_GOODS_USER u2
ON u1.WRITER_ID = u2.USER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES > 700000
ORDER BY TOTAL_SALES;

SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_USER UGU
JOIN USED_GOODS_BOARD UGB ON UGB.WRITER_ID = UGU.USER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;