-- 코드를 입력하세요
WITH MAX_MEM as (
    SELECT COUNT(*), MEMBER_ID
    FROM REST_REVIEW
    GROUP BY 2
    ORDER BY 1 DESC
    LIMIT 1
)
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE m JOIN REST_REVIEW r
ON m.MEMBER_ID = r.MEMBER_ID
JOIN MAX_MEM x
ON r.MEMBER_ID = x.MEMBER_ID
ORDER BY 3, 2