-- 코드를 작성해주세요
SELECT a.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_TREE a LEFT JOIN ITEM_INFO b
ON a.ITEM_ID = b.ITEM_ID
WHERE a.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY='RARE')
ORDER BY 1 DESC;
