-- 코드를 작성해주세요
WITH FISH_GROUP as (
    SELECT ID, FISH_TYPE, LENGTH,
    DENSE_RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) as rnk
    FROM FISH_INFO
)
SELECT ID, FISH_NAME, LENGTH
FROM FISH_GROUP a LEFT JOIN FISH_NAME_INFO b
ON a.FISH_TYPE = b.FISH_TYPE
WHERE rnk = 1
ORDER BY 1;
