-- 코드를 작성해주세요
SELECT SUM(c.SCORE) AS SCORE, b.EMP_NO, b.EMP_NAME, b.POSITION, b.EMAIL
FROM HR_DEPARTMENT a LEFT JOIN HR_EMPLOYEES b
ON a.DEPT_ID = b.DEPT_ID
LEFT JOIN HR_GRADE c
ON b.EMP_NO = c.EMP_NO
GROUP BY b.EMP_NO, c.YEAR
ORDER BY 1 DESC
LIMIT 1;