-- 코드를 입력하세요
SELECT b1.CATEGORY, SUM(b2.SALES) as TOTAL_SALES
FROM BOOK b1 INNER JOIN BOOK_SALES b2
ON b1.BOOK_ID = b2.BOOK_ID
WHERE b2.SALES_DATE LIKE '2022-01%'
GROUP BY b1.CATEGORY
ORDER BY b1.CATEGORY;